Repository Studio-Yandex-Practicum/adaptive_hockey_federation, pull requests merged in 2024-04, with the labels that each got.

#319 Изменил тип поля для города
  adaptive_hockey_federation/main/forms.py
Labels: bug

#296 В "Соревнованиях" у представителя команды убраны лишние кнопки и столбец
  adaptive_hockey_federation/competitions/views.py
  adaptive_hockey_federation/main/migrations/0019_alter_staffmember_phone.py
  adaptive_hockey_federation/templates/main/competitions/table.html
  adaptive_hockey_federation/templates/main/competitions_id/competitions_id.html
  adaptive_hockey_federation/templates/main/competitions_id/components/competition_teams_table_base.html
  adaptive_hockey_federation/tests/permissions_test.py
  adaptive_hockey_federation/tests/url_test.py
  pyproject.toml
Labels: bug

#328 Команда для создания тестовых данных на стейдже.
  adaptive_hockey_federation/core/management/commands/fill-test-stage.py
Labels: bug

#330 Представитель команды видет кнопки редактирования игроков только свое…
  adaptive_hockey_federation/main/migrations/0022_alter_document_file_alter_player_name_and_more.py
  adaptive_hockey_federation/templates/base/drawer.html
  adaptive_hockey_federation/templates/main/teams_id/create_delete_buttons.html
  adaptive_hockey_federation/templates/main/teams_id/edit_delete_button_players.html
  adaptive_hockey_federation/templates/main/teams_id/edit_delete_button_staffs.html
  adaptive_hockey_federation/templates/main/teams_id/table.html
  adaptive_hockey_federation/unloads/migrations/0005_alter_unload_unload_file_slug.py
  adaptive_hockey_federation/users/migrations/0008_alter_user_first_name_alter_user_last_name_and_more.py
Labels: bug, enhancement

#352 Реализована выгрузка Пользователей, а также перенес url для unloads
  .pre-commit-config.yaml
  adaptive_hockey_federation/core/urls.py
  adaptive_hockey_federation/core/utils.py
  adaptive_hockey_federation/main/urls.py
  adaptive_hockey_federation/parser/importing_db.py
  adaptive_hockey_federation/templates/base/drawer.html
  adaptive_hockey_federation/templates/base/footer.html
  adaptive_hockey_federation/templates/main/unloads/base_delete_buttons.html
  adaptive_hockey_federation/templates/main/unloads/table.html
  adaptive_hockey_federation/templates/main/unloads/unloads_delete.html
  adaptive_hockey_federation/unloads/mapping.py
  adaptive_hockey_federation/unloads/urls.py
  adaptive_hockey_federation/unloads/utils.py
  adaptive_hockey_federation/unloads/views.py
Labels: enhancement

#363 Убрано поле поиска, где оно не нужно.
  adaptive_hockey_federation/competitions/schema.py
  adaptive_hockey_federation/competitions/urls.py
  adaptive_hockey_federation/competitions/views.py
  adaptive_hockey_federation/core/config/base_settings.py
  adaptive_hockey_federation/core/context_processors.py
  adaptive_hockey_federation/main/schemas/main_schema.py
  adaptive_hockey_federation/templates/base/header.html
  adaptive_hockey_federation/users/utilits/send_mails.py
Labels: bug
