Repository Studio-Yandex-Practicum/adaptive_hockey_federation, pull requests merged in 2024-03, with the labels that each got.

#225 Исправлен баг с поиском в админ-панели
  adaptive_hockey_federation/main/admin/admin.py
Labels: bug

#229 Неудачная попытка валидации кода тел. страны # 205
  adaptive_hockey_federation/users/constants.py
  adaptive_hockey_federation/users/factories.py
  adaptive_hockey_federation/users/models.py
  adaptive_hockey_federation/users/provaders.py
  adaptive_hockey_federation/users/validators.py
Labels: bug

#238 Приложение events переименовано в competitions
  Makefile
  adaptive_hockey_federation/competitions/__init__.py
  adaptive_hockey_federation/competitions/admin.py
  adaptive_hockey_federation/competitions/apps.py
  adaptive_hockey_federation/competitions/forms.py
  adaptive_hockey_federation/competitions/migrations/0001_initial.py
  adaptive_hockey_federation/competitions/migrations/0002_alter_event_options.py
  adaptive_hockey_federation/competitions/migrations/__init__.py
  adaptive_hockey_federation/competitions/models.py
  adaptive_hockey_federation/competitions/urls.py
  adaptive_hockey_federation/competitions/utils.py
  adaptive_hockey_federation/competitions/validators.py
  adaptive_hockey_federation/competitions/views.py
  adaptive_hockey_federation/core/config/base_settings.py
  adaptive_hockey_federation/core/management/commands/fill-test-db.py
  adaptive_hockey_federation/core/urls.py
  adaptive_hockey_federation/events/migrations/0002_alter_event_options.py
  adaptive_hockey_federation/main/data_factories/factories.py
  adaptive_hockey_federation/templates/base/competition_button_create.html
  adaptive_hockey_federation/templates/base/drawer.html
  adaptive_hockey_federation/templates/base/footer.html
  adaptive_hockey_federation/templates/main/competitions/base_edit_delete_buttons.html
  adaptive_hockey_federation/templates/main/competitions/competition_edit_delete_buttons.html
  adaptive_hockey_federation/templates/main/competitions/table.html
  adaptive_hockey_federation/tests/url_test.py
Labels: refactoring

#240 Feature/search main
  adaptive_hockey_federation/main/controllers/main_views.py
  adaptive_hockey_federation/main/urls.py
  adaptive_hockey_federation/templates/base/header.html
  adaptive_hockey_federation/templates/base/search_form.html
  adaptive_hockey_federation/templates/main/home/main.html
  adaptive_hockey_federation/templates/main/home/search_form.html
  adaptive_hockey_federation/templates/main/home/table.html
Labels: enhancement

#257 Добавлено приложение unloads для выгрузки данных в формате excel
  .gitignore
  adaptive_hockey_federation/main/migrations/0015_alter_team_curator.py
  adaptive_hockey_federation/main/migrations/0018_alter_player_birthday_alter_player_gender_and_more.py
  adaptive_hockey_federation/main/views.py
  adaptive_hockey_federation/unloads/__init__.py
  adaptive_hockey_federation/unloads/admin.py
  adaptive_hockey_federation/unloads/apps.py
  adaptive_hockey_federation/unloads/migrations/__init__.py
  adaptive_hockey_federation/unloads/models.py
  adaptive_hockey_federation/unloads/utils.py
  adaptive_hockey_federation/unloads/views.py
  adaptive_hockey_federation/users/migrations/0006_alter_user_phone.py
Labels: enhancement

#259 #190. Права установлены. Вкладка -Аналитика- отображается только у админа.
  adaptive_hockey_federation/analytics/permissions.py
  adaptive_hockey_federation/analytics/views.py
  adaptive_hockey_federation/templates/base/drawer.html
Labels: enhancement

#273 Добавлена модель Unload, настроено добавление тестовых данных в бд
  adaptive_hockey_federation/core/config/base_settings.py
  adaptive_hockey_federation/core/management/commands/fill-test-db.py
  adaptive_hockey_federation/main/views.py
  adaptive_hockey_federation/unloads/admin.py
  adaptive_hockey_federation/unloads/factories.py
  adaptive_hockey_federation/unloads/migrations/0001_initial.py
  adaptive_hockey_federation/unloads/migrations/0002_alter_unload_name.py
  adaptive_hockey_federation/unloads/migrations/0003_alter_unload_name.py
  adaptive_hockey_federation/unloads/models.py
  adaptive_hockey_federation/unloads/utils.py
Labels: enhancement

#279 Feature/create models for unloads
  adaptive_hockey_federation/core/config/base_settings.py
  adaptive_hockey_federation/core/management/commands/fill-test-db.py
  adaptive_hockey_federation/main/views.py
  adaptive_hockey_federation/unloads/admin.py
  adaptive_hockey_federation/unloads/factories.py
  adaptive_hockey_federation/unloads/migrations/0001_initial.py
  adaptive_hockey_federation/unloads/migrations/0002_alter_unload_name.py
  adaptive_hockey_federation/unloads/migrations/0003_alter_unload_name.py
  adaptive_hockey_federation/unloads/migrations/0004_alter_unload_options_and_more.py
  adaptive_hockey_federation/unloads/models.py
  adaptive_hockey_federation/unloads/utils.py
  docs/ER_Diagram.drawio.xml
  docs/ER_Diagram.jpg
  qqq
Labels: enhancement

#251 Добавлены стили в форму редактирования игрока
  adaptive_hockey_federation/core/constants.py
  adaptive_hockey_federation/main/controllers/player_views.py
  adaptive_hockey_federation/main/forms.py
  adaptive_hockey_federation/staticfiles/css/base_style.css
  adaptive_hockey_federation/staticfiles/img/icon-unknown.svg
  adaptive_hockey_federation/staticfiles/img/search.svg
  adaptive_hockey_federation/staticfiles/img/selector-icons.svg
  adaptive_hockey_federation/staticfiles/js/selector.js
  adaptive_hockey_federation/templates/base/base.html
  adaptive_hockey_federation/templates/main/player_id/player_id_create_edit.html
Labels: refactoring

#274 Настройка sidebar и прав для разных ролей
  adaptive_hockey_federation/analytics/views.py
  adaptive_hockey_federation/core/config/base_settings.py
  adaptive_hockey_federation/core/permissions.py
  adaptive_hockey_federation/main/controllers/staff_views.py
  adaptive_hockey_federation/main/migrations/0019_alter_staffteammember_options.py
  adaptive_hockey_federation/main/models.py
  adaptive_hockey_federation/templates/base/competition_button_create.html
  adaptive_hockey_federation/templates/base/drawer.html
  adaptive_hockey_federation/templates/base/footer.html
  adaptive_hockey_federation/templates/main/competitions/base_edit_delete_buttons.html
  adaptive_hockey_federation/templates/main/player_id/edit_delete_buttons.html
  adaptive_hockey_federation/templates/main/staffs/staff_button_create.html
  adaptive_hockey_federation/templates/main/staffs/staffs_edit_delete_buttons.html
  adaptive_hockey_federation/templates/main/staffs/table.html
Labels: bug

#289 Feature/buttons edit and dellete in team
  adaptive_hockey_federation/main/controllers/team_views.py
  adaptive_hockey_federation/templates/main/teams_id/edit_delete_button_players.html
  adaptive_hockey_federation/templates/main/teams_id/edit_delete_button_staffs.html
  adaptive_hockey_federation/templates/main/teams_id/table.html
  adaptive_hockey_federation/templates/main/teams_id/teams_id.html
Labels: enhancement

#299 Добавлен полный функционал для модели Unloads
  adaptive_hockey_federation/main/urls.py
  adaptive_hockey_federation/main/views.py
  adaptive_hockey_federation/templates/base/footer.html
  adaptive_hockey_federation/templates/main/unloads/base_delete_buttons.html
  adaptive_hockey_federation/templates/main/unloads/table.html
  adaptive_hockey_federation/templates/main/unloads/unloads.html
  adaptive_hockey_federation/templates/main/unloads/unloads_delete.html
  adaptive_hockey_federation/unloads/utils.py
  adaptive_hockey_federation/unloads/views.py
Labels: enhancement

#312 bugfix: pagination.html
  adaptive_hockey_federation/templates/base/pagination.html
Labels: bug
